[package]
name = "lanta"
version = "0.1.0"
authors = ["Michael Killough <michaeljkillough@gmail.com>"]

[lib]
name = "lanta"
path = "src/lib.rs"

[[bin]]
name = "lanta"
path = "src/main.rs"
doc = false

[dependencies]
fern = "0.3.5"
libc = "0.2.21"
log = "0.3.7"
time = "0.1.37"
xdg = "2.1.0"

[dependencies.x11]
version = "2.12.1"
features = ["xlib"]
