[package]
name = "lanta"
version = "0.1.0"
authors = ["Michael Killough <michaeljkillough@gmail.com>"]

[lib]
name = "lanta"
path = "src/lib.rs"

[[bin]]
name = "lanta"
path = "src/main.rs"
doc = false

[dependencies]
fern = "0.3.5"
libc = "0.2.21"
log = "0.3.7"
time = "0.1.37"
xdg = "2.1.0"
xcb = "0.7.6"
x11 = "2.12.1"

[dependencies.xcb-util]
path = "./xcb-util"
features = ["ewmh", "icccm", "keysyms"]
