[package]
name = "rwm"
version = "0.1.0"
authors = ["Michael Killough <michaeljkillough@gmail.com>"]

[dependencies]
log = "0.3.7"
env_logger = "0.4.2"
libc = "0.2.21"

[dependencies.x11]
version = "2.12.1"
features = ["xlib"]
